project:
  type: website
  output-dir: docs

website:
  title: "300 Views"
  navbar:
    right:
      - about.qmd
      - icon: github
        href: https://github.com/kpjmcg
      - icon: twitter
        href: https://twitter.com/kieran_mcgee/
  twitter-card: true
format:
  html:
    theme: 
      light: flatly
      dark: darkly
    css: styles.css



