project:
  type: website
  output-dir: docs

website:
  title: "blog"
  navbar:
    right:
      - about.qmd
      - icon: github
        href: https://github.com/kpjmcg
      - icon: twitter
        href: https://twitter.com/kieran_mcgee/
format:
  html:
    theme: flatly
    css: styles.css



